#if !defined(SRC__LIFECYCLEMGR__INC__LIFECYCLE_MGR_LIFECYCLE_STATE_H)
#define      SRC__LIFECYCLEMGR__INC__LIFECYCLE_MGR_LIFECYCLE_STATE_H
//***********************************************************************************
/// \file
/// Lifecycle Manager Lifecycle States
///
/// \addtogroup lifecyclemgr   Lifecycle Manager
/// @{
//***********************************************************************************
// Copyright 2018 ON Semiconductor.  All rights reserved.
//
// This software and/or documentation is licensed by ON Semiconductor under limited
// terms and conditions. The terms and conditions pertaining to the software and/or
// documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf
// ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").
// Do not use this software and/or documentation unless you have carefully read and
// you agree to the limited terms and conditions. By using this software and/or
// documentation, you agree to the limited terms and conditions.
//***********************************************************************************

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// DO NOT EDIT - This file is auto-generated by the generate_lifecycle_states.py script
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

//------------------------------------------------------------------------------
//                           Lifecycle Manager States
//------------------------------------------------------------------------------

// *INDENT-OFF*

/// Lifecycle states
typedef enum
{
    LIFECYCLE_MGR_LIFECYCLE_STATE_CM = 0x00U,          ///< Chip Manufacture
    LIFECYCLE_MGR_LIFECYCLE_STATE_DM = 0x01U,          ///< Device Manufacture
    LIFECYCLE_MGR_LIFECYCLE_STATE_SECURE = 0x02U,      ///< Secure
    LIFECYCLE_MGR_LIFECYCLE_STATE_RMA = 0x03U,         ///< RMA
} LifecycleMgrLifecycleStateT;

/// @} endgroup lifecyclemgr
#endif  // !defined(SRC__LIFECYCLEMGR__INC__LIFECYCLE_MGR_LIFECYCLE_STATE_H)

