#######################################################################################
# Copyright 2018 ON Semiconductor.  All rights reserved.
#
# This software and/or documentation is licensed by ON Semiconductor under limited
# terms and conditions.  The terms and conditions pertaining to the software and/or
# documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf
# ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Softwar").
# Do not use this software and/or documentation unless you have carefully read and
# you agree to the limited terms and conditions.  By using this software and/or
# documentation, you agree to the limited terms and conditions.
########################################################################################
#
# Generates C and Python operation error code header files from a master CSV file
#
########################################################################################
import argparse
import csv
import os
import sys

class ErrorGenerator():
    """Operation error code header generator class
    """

    C_HEADER = \
        '#ifndef INC__COMMON_ERROR_H\n' \
        '#define INC__COMMON_ERROR_H\n' \
        '//***********************************************************************************\n' \
        '/// \\file\n' \
        '///\n' \
        '/// Common operation error codes\n' \
        '///\n' \
        '//***********************************************************************************\n' \
        '// Copyright 2018 ON Semiconductor.  All rights reserved.\n' \
        '//\n' \
        '// This software and/or documentation is licensed by ON Semiconductor under limited\n' \
        '// terms and conditions. The terms and conditions pertaining to the software and/or\n' \
        '// documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf\n' \
        '// ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").\n' \
        '// Do not use this software and/or documentation unless you have carefully read and\n' \
        '// you agree to the limited terms and conditions. By using this software and/or\n' \
        '// documentation, you agree to the limited terms and conditions.\n' \
        '//***********************************************************************************\n' \
        '\n' \
        '// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' \
        '// DO NOT EDIT - This file is auto-generated by the generate_errors.py script\n' \
        '// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' \
        '\n' \
        '//------------------------------------------------------------------------------\n' \
        '//                             Operation Error Codes\n' \
        '//------------------------------------------------------------------------------\n' \
        '\n' \
        '// *INDENT-OFF*\n' \
        '\n' \
        '/// Operation error codes\n' \
        'typedef enum\n' \
        '{\n'

    C_FOOTER = \
        '} ErrorT;\n' \
        '\n' \
        '#endif  // !defined(INC__COMMON_ERROR_H)\n' \
        '\n'

    PYTHON_HEADER = \
        '####################################################################################\n' \
        '# Copyright 2018 ON Semiconductor.  All rights reserved.\n' \
        '#\n' \
        '# This software and/or documentation is licensed by ON Semiconductor under limited\n' \
        '# terms and conditions. The terms and conditions pertaining to the software and/or\n' \
        '# documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf\n' \
        '# ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").\n' \
        '# Do not use this software and/or documentation unless you have carefully read and\n' \
        '# you agree to the limited terms and conditions. By using this software and/or\n' \
        '# documentation, you agree to the limited terms and conditions.\n' \
        '#\n' \
        '####################################################################################\n' \
        '\n' \
        '#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' \
        '# DO NOT EDIT - This file is auto-generated by the generate_errors.py script\n' \
        '#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' \
        '\n' \
        'from enum import IntEnum, unique\n' \
        '\n' \
        '@unique\n' \
        'class Error(IntEnum):\n' \
        '    """Operation error codes enumeration."""\n'

    PYTHON_FOOTER = \
        '\n' \
        '    def __str__(self):\n' \
        '        return \'0x{:04X}:{}\'.format(self.value, self.name)\n' \
        '\n'

    def __init__(self, csv_filename, prefix, debug=False):
        self._csv_filename = csv_filename
        self._prefix = prefix
        self._debug = debug

    def validate(self):
        """Checks for duplicate error code values
        """
        if self._debug: print("Validating error codes...")
        found_entries = list()

        with open(self._csv_filename, newline='') as csvfile:
            entries = csv.DictReader(csvfile)
            for row in entries:
                if "" != row['Name'].strip():
                    error_name = row['Name'].strip()
                    error_value = int(row['Value'].strip(), 16)

                    if self._debug: print("Evaluating error code: {}: {}".format(error_name, error_value))

                    # Look for a duplicate
                    for (existing_error_value, existing_error_name) in found_entries:
                        if existing_error_value == error_value:
                            raise Exception("Duplicate error_code found: {} duplicates {}\n".format(error_name, existing_error_name))

                    found_entries.append((error_value, error_name))

        if self._debug: print("All error codes valid\n")

    def generate_c(self, filename):
        """Generates the C .h header file.
        """
        if self._debug:
            print("Generating C error codes...")

        # Build the C error codes content
        content = self.C_HEADER

        with open(self._csv_filename, newline='') as csvfile:
            entries = csv.DictReader(csvfile)
            next_error = 0
            for row in entries:
                if "" != row['Name'].strip():
                    if int(row['Value'].strip()) != next_error:
                        content += '\n'
                        next_error = int(row['Value'].strip()) + 1
                    else:
                        next_error += 1
                    nameValue = '{}_{} = {}U,'.format(self._prefix, row['Name'].strip(), row['Value'].strip())
                    content += "    {:25s} ///< 0x{:04X}: {}\n".format(\
                        nameValue, int(row['Value'].strip()), row['Comment'].strip())

        content += self.C_FOOTER

        # write the C error codes content
        if self._debug: print("Writing {}...".format(filename))
        with open(filename, "wt", newline='\n') as ostream:
            ostream.write(content)

    def generate_python(self, filename):
        """Generates the Python .py header file.
        """
        if self._debug:
            print("Generating Python error codes...")

        # Build the Python error codes content
        content = self.PYTHON_HEADER

        with open(self._csv_filename, newline='') as csvfile:
            entries = csv.DictReader(csvfile)
            next_error = 0
            for row in entries:
                if "" != row['Name'].strip():
                    if int(row['Value'].strip()) != next_error:
                        content += '\n'
                        next_error = int(row['Value'].strip()) + 1
                    else:
                        next_error += 1
                    nameValue = '    {} = {}'.format(row['Name'].strip(), row['Value'].strip())
                    content += "{:20s}  # 0x{:04X}: {}\n".format(\
                        nameValue, int(row['Value'].strip()), row['Comment'].strip())

        content += self.PYTHON_FOOTER

        # write the Python error codes content
        if self._debug: print("Writing {}...".format(filename))
        with open(filename, "wt", newline='\n') as ostream:
            ostream.write(content)

# Create the argument parser
parser = argparse.ArgumentParser(prog='generate_errors',
    description='Generate C and Python header files for operation error codes')
parser.add_argument('-d', '--debug', default=False, action='store_true', help='Enable debug output')
parser.add_argument('-c', '--csvfile', required=True, help='Operation error code master CSV file')
parser.add_argument('-o', '--output', required=True, help='Output directory for ASM and C header files')
parser.add_argument('-s', '--scripts', required=True, help='Output directory for Python scripts')
parser.add_argument('-v', '--validate', required=False, action='store_true', help='Validate error codes')

# Parse the command line arguments
args = parser.parse_args()

generator = ErrorGenerator(args.csvfile, 'ERROR', args.debug)
if args.validate:
    generator.validate()

# Generate C and Python operation error code header files
print('Generating operation error codes...')
generator.generate_c(os.path.join(args.output, 'CommonError.h'))
generator.generate_python(os.path.join(args.scripts, 'common_error.py'))
