#if !defined(SRC__SYSTEMMGR__INC__SYSTEMMGRPHASE_H)
#define      SRC__SYSTEMMGR__INC__SYSTEMMGRPHASE_H
//***********************************************************************************
/// \file
/// System Manager public API - phases
///
/// \addtogroup systemmgr   System Manager
/// @{
//***********************************************************************************
// Copyright 2018 ON Semiconductor.  All rights reserved.
//
// This software and/or documentation is licensed by ON Semiconductor under limited
// terms and conditions. The terms and conditions pertaining to the software and/or
// documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf
// ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").
// Do not use this software and/or documentation unless you have carefully read and
// you agree to the limited terms and conditions. By using this software and/or
// documentation, you agree to the limited terms and conditions.
//***********************************************************************************

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// DO NOT EDIT - This file is auto-generated by the generate_system_phases.py script
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

//------------------------------------------------------------------------------
//                             System Manager Phases
//------------------------------------------------------------------------------

// *INDENT-OFF*

/// System phases
typedef enum
{
    SYSTEM_MGR_PHASE_BOOT = 0x00U,           ///< Default phase at boot
    SYSTEM_MGR_PHASE_INITIALIZE = 0x01U,     ///< Initialize phase
    SYSTEM_MGR_PHASE_DEBUG = 0x02U,          ///< Debug phase
    SYSTEM_MGR_PHASE_PATCH = 0x03U,          ///< Patch phase
    SYSTEM_MGR_PHASE_CONFIGURE = 0x04U,      ///< Configure phase
    SYSTEM_MGR_PHASE_SESSION = 0x05U,        ///< Session phase
    SYSTEM_MGR_PHASE_SHUTDOWN = 0x06U,       ///< Shutdown phase
    SYSTEM_MGR_PHASE_NUM_PHASES = 0x07U,     ///< Used for unit testing only
} SystemMgrPhaseT;

/// @} endgroup systemmgr
#endif  // !defined(SRC__SYSTEMMGR__INC__SYSTEMMGRPHASE_H)

