#ifndef INC__COMMON_ERROR_H
#define INC__COMMON_ERROR_H
//***********************************************************************************
/// \file
///
/// Common operation error codes
///
//***********************************************************************************
// Copyright 2018 ON Semiconductor.  All rights reserved.
//
// This software and/or documentation is licensed by ON Semiconductor under limited
// terms and conditions. The terms and conditions pertaining to the software and/or
// documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf
// ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").
// Do not use this software and/or documentation unless you have carefully read and
// you agree to the limited terms and conditions. By using this software and/or
// documentation, you agree to the limited terms and conditions.
//***********************************************************************************

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// DO NOT EDIT - This file is auto-generated by the generate_errors.py script
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

//------------------------------------------------------------------------------
//                             Operation Error Codes
//------------------------------------------------------------------------------

// *INDENT-OFF*

/// Operation error codes
typedef enum
{
    ERROR_SUCCESS = 0U,       ///< 0x0000: Operation successful
    ERROR_NOENT = 1U,         ///< 0x0001: No entry found
    ERROR_SYSERR = 2U,        ///< 0x0002: System error occurred
    ERROR_IO = 3U,            ///< 0x0003: I/O error occurred
    ERROR_NODEV = 4U,         ///< 0x0004: No device or object found

    ERROR_AGAIN = 6U,         ///< 0x0006: Try again

    ERROR_ACCESS = 8U,        ///< 0x0008: Permission denied
    ERROR_BUSY = 9U,          ///< 0x0009: Busy

    ERROR_INVAL = 12U,        ///< 0x000C: Invalid parameter or argument
    ERROR_NOSPC = 13U,        ///< 0x000D: No memory or resource available
    ERROR_RANGE = 14U,        ///< 0x000E: Parameter or argument out-of-range

    ERROR_ALREADY = 16U,      ///< 0x0010: Operation already in-progress or done
    ERROR_CANCELLED = 17U,    ///< 0x0011: Operation cancelled
    ERROR_TIMEDOUT = 18U,     ///< 0x0012: Operation timed-out
    ERROR_BADMSG = 19U,       ///< 0x0013: Malformed message or parameter
    ERROR_NOMSG = 20U,        ///< 0x0014: No message found
    ERROR_NOEXEC = 21U,       ///< 0x0015: Cannot execute
} ErrorT;

#endif  // !defined(INC__COMMON_ERROR_H)

