####################################################################################
# Copyright 2018 ON Semiconductor.  All rights reserved.
#
# This software and/or documentation is licensed by ON Semiconductor under limited
# terms and conditions. The terms and conditions pertaining to the software and/or
# documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf
# ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").
# Do not use this software and/or documentation unless you have carefully read and
# you agree to the limited terms and conditions. By using this software and/or
# documentation, you agree to the limited terms and conditions.
#
####################################################################################

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DO NOT EDIT - This file is auto-generated by the generate_css_faults.py script
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

from enum import IntEnum, unique

@unique
class SystemMgrCssFault(IntEnum):
    """CSS fault enumeration."""

    NONE = 0x00                                          # (0) None
    WATCHDOG = 0x01                                      # (1) Processor watchdog expired (firmware dead-lock/runaway)
    FIRMWARE_FATAL = 0x02                                # (2) Firmware detected fatal error
    FIRMWARE_TERMINATED = 0x03                           # (3) Firmware normal termination
    CRYPTOCELL_SW_ERROR = 0x04                           # (4) Cryptocell software reported error
    CRYPTOCELL_HW_ERROR = 0x05                           # (5) Cryptocell hardware reported error
    CMAC_ENGINE_ERROR = 0x06                             # (6) CMAC hardware reported error
    GMAC_ENGINE_ERROR = 0x07                             # (7) GMAC hardware reported error
    OTPM_ERROR = 0x08                                    # (8) OTPM hardware reported error
    ICORE_ECC_FAILURE = 0x09                             # (9) ICore shared-memory ECC DED
    PROCESSOR_LOCKUP = 0x0A                              # (10) Processor LOCK_UP signal asserted (firmware terminated)
    PROCESSOR_STATE = 0x0B                               # (11) Processor state is incorrect
    HARDFAULT = 0x0C                                     # (12) HardFault handler triggered
    UNEXPECTED_EXCEPTION = 0x0D                          # (13) Unexpected exception or interrupt
    ROM_ECC_FAILURE = 0x0E                               # (14) Processor ROM ECC failure
    RAM_ECC_FAILURE = 0x0F                               # (15) Processor RAM ECC failure
    STACK_OVERFLOW = 0x10                                # (16) RAM stack overflow failure

    MAX = 0x3F                                           # (63) Maximum fault code value

    def __str__(self):
        return '0x{:04X}:{}'.format(self.value, self.name)

