//******************************************************************************
/// \file
///
/// This file implements the basic Hard Fault handler for CppUTest
///
/// \addtogroup init
/// @{
//******************************************************************************
// Copyright 2018 ON Semiconductor. All rights reserved. This software and/or
// documentation is licensed by ON Semiconductor under limited terms and
// conditions. The terms and conditions pertaining to the software and/or
// documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf
// ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").
// Do not use this software and/or documentation unless you have carefully read
// and you agree to the limited terms and conditions. By using this software
// and/or documentation, you agree to the limited terms and conditions.
//******************************************************************************

#include <stdio.h>

#include "Common.h"
#include "AR0820.h"
#include "SystemMgr.h"

//------------------------------------------------------------------------------
//                                  Types
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//                                  Constants
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//                                  Locals
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//                                  Exports
//------------------------------------------------------------------------------

/// Handles a hard fault (invoked by assembler wrapper)
///
/// Hard faults can happen for the following reasons:
///
/// | Fault Class  | Fault Condition                                            |
/// |:------------:|:-----------------------------------------------------------|
/// |Memory related| 1. Bus error (can be program accesses or data accesses,    |
/// |              |    also referred to as bus faults in Cortex-M3):           |
/// |              |    a. Bus error generated by bus infrastructure because of |
/// |              |       an invalid address during bus transaction            |
/// |              |    b. Bus error generated by bus slave                     |
/// |              | 2. Attempt to execute the program from a memory region     |
/// |              |    marked as nonexecutable                                 |
/// | Program error| 3. Execution of undefined instruction                      |
/// |(usage faults)| 4. Trying to switch to ARM state (Cortex-M0+ only supports |
/// |              |    Thumb instructions)                                     |
/// |              | 5. Attempt to generate an unaligned memory access (not     |
/// |              |    allowed in ARMv6-M)                                     |
/// |              | 6. Attempt to execute an SVC when the SVC exception        |
/// |              |    priority level is the same or lower than the current    |
/// |              |    exception level                                         |
/// |              | 7. Invalid EXC_RETURN value during exception return        |
/// |              | 8. Attempt to execute a breakpoint instruction (BKPT) when |
/// |              |    debug is not enabled (no debugger attached)             |
///
/// \param[in] FramePtr     Points to the stacked exception frame
/// \param[in] LinkReg      The current LR value
/// \param[in] ControlReg   The current CONTROL value
/// \returns Never
///
void InitHardFaultHandler(uint32_t* FramePtr, uint32_t LinkReg, uint32_t ControlReg)
{
    xPSR_Type* xPSR = (xPSR_Type*)&FramePtr[7];

    printf("!!! HARDFAULT !!!\n");
    printf("R0  = 0x%08lx R1 = 0x%08lx R2 = 0x%08lx R3   = 0x%08lx\n",
        FramePtr[0], FramePtr[1], FramePtr[2], FramePtr[3]);
    printf("R12 = 0x%08lx LR = 0x%08lx PC = 0x%08lx xPSR = 0x%08lx\n",
        FramePtr[4], FramePtr[5], FramePtr[6], FramePtr[7]);
    printf("currLR = 0x%08lx\n", LinkReg);
    printf("Exception# = 0x%08x\n", xPSR->b.ISR);

    //
    // Attempt to determine the cause of the HardFault
    //
    if (0 == xPSR->b.T)
    {
        printf("Thumb bit clear, wrong ARM state\n");
    }

    if (0 != ControlReg)
    {
        printf("Control is non-zero (0x%08x)\n", ControlReg);
    }

    while (true)
    {
    }
}

/// @} endgroup init

