#######################################################################################
# Copyright 2018 ON Semiconductor.  All rights reserved.
#
# This software and/or documentation is licensed by ON Semiconductor under limited
# terms and conditions.  The terms and conditions pertaining to the software and/or
# documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf
# ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Softwar").
# Do not use this software and/or documentation unless you have carefully read and
# you agree to the limited terms and conditions.  By using this software and/or
# documentation, you agree to the limited terms and conditions.
########################################################################################
#
# Generates C and Python host command code header files from a master CSV file
#
########################################################################################
import argparse
import csv
import os
import sys

class HostCommandCodeGenerator():
    """Host command code header generator class
    """

    C_HEADER = \
        '#ifndef COMMAND_HANDLER_HOST_COMMAND_CODE_H\n' \
        '#define COMMAND_HANDLER_HOST_COMMAND_CODE_H\n' \
        '//***********************************************************************************\n' \
        '/// \\file\n' \
        '///\n' \
        '/// Host commands.\n' \
        '///\n' \
        '//***********************************************************************************\n' \
        '// Copyright 2018 ON Semiconductor.  All rights reserved.\n' \
        '//\n' \
        '// This software and/or documentation is licensed by ON Semiconductor under limited\n' \
        '// terms and conditions. The terms and conditions pertaining to the software and/or\n' \
        '// documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf\n' \
        '// ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").\n' \
        '// Do not use this software and/or documentation unless you have carefully read and\n' \
        '// you agree to the limited terms and conditions. By using this software and/or\n' \
        '// documentation, you agree to the limited terms and conditions.\n' \
        '//***********************************************************************************\n' \
        '\n' \
        '// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' \
        '// DO NOT EDIT - This file is auto-generated by the generate_commands.py script\n' \
        '// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' \
        '\n' \
        '//------------------------------------------------------------------------------\n' \
        '//                                 Host Commands\n' \
        '//------------------------------------------------------------------------------\n' \
        '\n' \
        '// *INDENT-OFF*\n' \
        '\n' \
        '/// Host command codes\n' \
        'typedef enum\n' \
        '{'

    C_FOOTER = \
        '} HostCommandCodeT;\n' \
        '\n' \
        '#endif /* COMMAND_HANDLER_HOST_COMMAND_CODE_H */\n' \
        '\n'

    PYTHON_HEADER = \
        '####################################################################################\n' \
        '# Copyright 2018 ON Semiconductor.  All rights reserved.\n' \
        '#\n' \
        '# This software and/or documentation is licensed by ON Semiconductor under limited\n' \
        '# terms and conditions. The terms and conditions pertaining to the software and/or\n' \
        '# documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf\n' \
        '# ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").\n' \
        '# Do not use this software and/or documentation unless you have carefully read and\n' \
        '# you agree to the limited terms and conditions. By using this software and/or\n' \
        '# documentation, you agree to the limited terms and conditions.\n' \
        '#\n' \
        '####################################################################################\n' \
        '\n' \
        '#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' \
        '# DO NOT EDIT - This file is auto-generated by the generate_commands.py script\n' \
        '#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n' \
        '\n' \
        'from enum import IntEnum, unique\n' \
        '\n' \
        '@unique\n' \
        'class HostCommandCode(IntEnum):\n' \
        '    """CommandHandler host command code enumeration."""\n'

    PYTHON_FOOTER = \
        '\n' \
        '    def __str__(self):\n' \
        '        return \'0x{:04X}:{}\'.format(self.value, self.name)\n' \
        '\n'

    def __init__(self, csv_filename, prefix, debug=False):
        self._csv_filename = csv_filename
        self._prefix = prefix
        self._debug = debug

    def validate(self):
        """Checks for duplicate host command values
        """
        if self._debug: print("Validating command codes...")
        found_commands = list()

        with open(self._csv_filename, newline='') as csvfile:
            commands = csv.DictReader(csvfile)
            for row in commands:
                if "" != row['Name'].strip():
                    command_name = row['Name'].strip()
                    command_value = int(row['Value'].strip(), 16)

                    if self._debug: print("Evaluating host command: {}: {}".format(command_name, command_value))

                    # Look for a duplicate
                    for (existing_command_value, existing_command_name) in found_commands:
                        if existing_command_value == command_value:
                            raise Exception("Duplicate host command found: {} duplicates {}\n".format(command_name, existing_command_name))

                    found_commands.append((command_value, command_name))

        if self._debug: print("All host commands valid\n")

    def generate_c(self, filename):
        """Generates the C .h header file.
        """
        if self._debug:
            print("Generating C host commands...")

        # Build the C host command content
        content = self.C_HEADER

        with open(self._csv_filename, newline='') as csvfile:
            commands = csv.DictReader(csvfile)
            next_command = 1
            for row in commands:
                if "" != row['Name'].strip():
                    if int(row['Value'].strip(), 16) != next_command:
                        content += '\n'
                        next_command = int(row['Value'].strip(), 16) + 1
                    else:
                        next_command += 1
                    nameValue = '{}_{} = {}U,'.format(self._prefix, row['Name'].strip(), row['Value'].strip())
                    content += "    {:57s} ///< (0x{:04X}) {}\n".format(\
                        nameValue, int(row['Value'].strip(), 16), row['Comment'].strip())

        content += self.C_FOOTER

        # write the C host commands content
        if self._debug: print("Writing {}...".format(filename))
        with open(filename, "wt", newline='\n') as ostream:
            ostream.write(content)

    def generate_python(self, filename):
        """Generates the Python .py header file.
        """
        if self._debug:
            print("Generating Python host commands...")

        # Build the Python host command content
        content = self.PYTHON_HEADER

        with open(self._csv_filename, newline='') as csvfile:
            commands = csv.DictReader(csvfile)
            next_command = 1
            for row in commands:
                if "" != row['Name'].strip():
                    if int(row['Value'].strip(), 16) != next_command:
                        content += '\n'
                        next_command = int(row['Value'].strip(), 16) + 1
                    else:
                        next_command += 1
                    nameValue = '    {} = {}'.format(row['Name'].strip(), row['Value'].strip())
                    content += "{:40s}  # (0x{:04X}) {}\n".format(\
                        nameValue, int(row['Value'].strip(), 16), row['Comment'].strip())

        content += self.PYTHON_FOOTER

        # write the Python host command content
        if self._debug: print("Writing {}...".format(filename))
        with open(filename, "wt", newline='\n') as ostream:
            ostream.write(content)

# Create the argument parser
parser = argparse.ArgumentParser(prog='generate_commands',
    description='Generate C and Python header files for CommandHandler host command codes')
parser.add_argument('-d', '--debug', default=False, action='store_true', help='Enable debug output')
parser.add_argument('-c', '--csvfile', required=True, help='Host command code master CSV file')
parser.add_argument('-o', '--output', required=True, help='Output directory for ASM and C header files')
parser.add_argument('-s', '--scripts', required=True, help='Output directory for Python scripts')
parser.add_argument('-v', '--validate', required=False, action='store_true', help='Validate host commands')

# Parse the command line arguments
args = parser.parse_args()

generator = HostCommandCodeGenerator(args.csvfile, 'HOST_COMMAND_CODE', args.debug)
if args.validate:
    generator.validate()

# Generate C and Python host command code header files
print('Generating host command codes...')
generator.generate_c(os.path.join(args.output, 'CommandHandlerHostCommandCode.h'))
generator.generate_python(os.path.join(args.scripts, 'host_command_code.py'))
