####################################################################################
# Copyright 2018 ON Semiconductor.  All rights reserved.
#
# This software and/or documentation is licensed by ON Semiconductor under limited
# terms and conditions. The terms and conditions pertaining to the software and/or
# documentation are available at http://www.onsemi.com/site/pdf/ONSEMI_T&C.pdf
# ("ON Semiconductor Standard Terms and Conditions of Sale, Section 8 Software").
# Do not use this software and/or documentation unless you have carefully read and
# you agree to the limited terms and conditions. By using this software and/or
# documentation, you agree to the limited terms and conditions.
#
####################################################################################

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DO NOT EDIT - This file is auto-generated by the generate_errors.py script
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

from enum import IntEnum, unique

@unique
class Error(IntEnum):
    """Operation error codes enumeration."""
    SUCCESS = 0       # 0x0000: Operation successful
    NOENT = 1         # 0x0001: No entry found
    SYSERR = 2        # 0x0002: System error occurred
    IO = 3            # 0x0003: I/O error occurred
    NODEV = 4         # 0x0004: No device or object found

    AGAIN = 6         # 0x0006: Try again

    ACCESS = 8        # 0x0008: Permission denied
    BUSY = 9          # 0x0009: Busy

    INVAL = 12        # 0x000C: Invalid parameter or argument
    NOSPC = 13        # 0x000D: No memory or resource available
    RANGE = 14        # 0x000E: Parameter or argument out-of-range

    ALREADY = 16      # 0x0010: Operation already in-progress or done
    CANCELLED = 17    # 0x0011: Operation cancelled
    TIMEDOUT = 18     # 0x0012: Operation timed-out
    BADMSG = 19       # 0x0013: Malformed message or parameter
    NOMSG = 20        # 0x0014: No message found
    NOEXEC = 21       # 0x0015: Cannot execute

    def __str__(self):
        return '0x{:04X}:{}'.format(self.value, self.name)

